name: awwaab_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.3
  font_awesome_flutter: ^10.12.0
  get_it: ^9.2.0
  injectable: ^2.7.1+2
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.9.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2

dependency_overrides:
  analyzer: ^6.4.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: 0.14.4
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/awwaab_iccon.png"
  adaptive_icon_background: "#1F3C2E"
  adaptive_icon_foreground: "assets/icons/awwaab_iccon.png"
  app_name: "أَوَّابٌ"
  min_sdk_android: 21

# flutter_native_splash:
#   color: "#1F3C2E"           
#   image: assets/icons/logo.png  
#   branding: assets/icons/logo.png 
  
#   android_12: 
#     image: assets/icons/logo.png
#     icon_background_color: "#1F3C2E"
  
#   android: true
#   ios: true
#   fullscreen: true  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
